services:
  - type: web
    name: trueface-backend
    env: python
    plan: free
    rootDir: trueface_flask_app
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
